### ISSUE TITLE
[BUG] Cannot Install the package (1.5.10) using git and pip

### ISSUE THREAD

**Issue by kiarash13p** [Loop3D/LoopStructural#159]
### Describe your issue

Recently, I tried to install the package by pip and git commands, but eventually, I received the following error. It seems there are some conflicts among packages versions and I would be thankful to have your guidance regarding this issue.

To be noted, I previously faced egg_info error but I could fix that by updating all required packages.

### Minimal reproducing code example

```python
No external Coding yet.
```

### Error message

```shell
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\kpashna\Documents\GitHub\loopstructural_intrusions_gmd_paper2023\Virtual Env\Env\loopstructural\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\kpashna\Documents\GitHub\loopstructural_intrusions_gmd_paper2023\Virtual Env\Env\loopstructural\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kpashna\Documents\GitHub\loopstructural_intrusions_gmd_paper2023\Virtual Env\Env\loopstructural\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kpashna\AppData\Local\Temp\pip-build-env-p6vb_r7q\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\kpashna\AppData\Local\Temp\pip-build-env-p6vb_r7q\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\kpashna\AppData\Local\Temp\pip-build-env-p6vb_r7q\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\kpashna\AppData\Local\Temp\pip-build-env-p6vb_r7q\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      RuntimeError: Cannot import cython
      python -m pip install cython
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by lachlangrose** [comment]
Hi, @kiarash13p you need to install cython before installing loopstructural it you are installing loopstructural from source.

**Comment by kiarash13p** [comment]
Many thanks @lachlangrose for your reply. I checked again the installed packages and it seems that cython has already being installed on my operating system.

This time however, I received a different error but still cannot install the package.

![image](https://github.com/Loop3D/LoopStructural/assets/47757629/2b42bd7e-909d-4c7a-ac2c-fce60172da4d)

I am pretty sure that something is wrong on my side, but I am not able to track it! I appreciate for suggestions and comments,

Regards,

**Comment by lachlangrose** [comment]
No problem. Looking at the error message it looks like the cython files aren't found. It means that the python package doesn't include the correct files, I will have to update this. 

In the meantime you should be able to install using `pip install git+https://github.com/Loop3D/LoopStructural.git`

**Comment by kiarash13p** [comment]
Many thanks for your help. I could install 1.5.10 via git. I am facing different errors in code but they are not relevant to this topic, so I will close it if you don't mind.

Just a note that the package 'lavavu' is not considered during the installation as a prerequisite, and needs to be installed separately.
