### ISSUE TITLE
[BUG] Fault error

### ISSUE THREAD

**Issue by awickert** [Loop3D/LoopStructural#62]
The fault example returns the following when I run it:

```
andy@cuesta:~/dataanalysis/LoopStructural/examples/3_fault$ python3 plot_faulted_intrusion.py 
Traceback (most recent call last):
  File "plot_faulted_intrusion.py", line 91, in <module>
    viewer.add_isosurface(strati,
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/visualisation/model_visualisation.py", line 264, in add_isosurface
    val = geological_feature.evaluate_value(points)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature.py", line 126, in evaluate_value
    self.builder.up_to_date()
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 89, in up_to_date
    self.update()
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 78, in update
    self.build(**self.build_arguments)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 379, in build
    self.add_data_to_interpolator(**kwargs)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 172, in add_data_to_interpolator
    data.loc[:,xyz_names()] = f.apply_to_points(
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/fault/fault_segment.py", line 244, in apply_to_points
    gx = gx_future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature.py", line 126, in evaluate_value
    self.builder.up_to_date()
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 89, in up_to_date
    self.update()
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 78, in update
    self.build(**self.build_arguments)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/modelling/features/geological_feature_builder.py", line 412, in build
    self.interpolator.solve_system(**kwargs)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/interpolators/geological_interpolator.py", line 179, in solve_system
    self._solve(**kwargs)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/interpolators/discrete_interpolator.py", line 509, in _solve
    A, B = self.build_matrix(damp=damp)
  File "/home/andy/.local/lib/python3.8/site-packages/LoopStructural/interpolators/discrete_interpolator.py", line 317, in build_matrix
    BT = A.T.dot(B)
  File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 363, in dot
    return self * other
  File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 499, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
```

Would it be possible to verify whether this is reproducible? I am using v1.0.89 via pip3.

**Comment by lachlangrose** [comment]
This seems to be because the model is interpolated when being added to the visualisation. It goes away if 
`model.update()` is added before the visualisation. 

The model should be updated when it is added to the visualisation so I suspect the order the scalar fields are being interpolated is wrong and causes the issues. I'll update the example, but keep this open.

**Comment by awickert** [comment]
I will pull once you update, then test, then close if it works.

**Comment by awickert** [comment]
I updated to 1.0.9 after uninstalling the pip version of LoopStructural. The fault example then successfully run and gave these output images:
![default](https://user-images.githubusercontent.com/1714966/111304890-4c2e9d00-8624-11eb-8031-878a00fe8573.png)
![default-00001](https://user-images.githubusercontent.com/1714966/111304893-4cc73380-8624-11eb-82c4-204ccc4cd9e2.png)
